name: consentLens cron

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch:        

jobs:
  keep-awake:
    runs-on: ubuntu-latest

    steps:
      - name: Curl the Render App
        run: |
          curl -sSf https://consent-lens-alpha.vercel.app || echo "Ping failed"
